name: module3_task0
on:
  push:
    branches: [$default-branch]
  schedule:
    - cron: '5 9 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run check make
        run: make help
